/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AddressUpdateManyWithoutContactPeopleInput } from "./AddressUpdateManyWithoutContactPeopleInput";
import { ValidateNested, IsOptional, IsString, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { OrderUpdateManyWithoutContactPeopleInput } from "./OrderUpdateManyWithoutContactPeopleInput";

@InputType()
class ContactPersonUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AddressUpdateManyWithoutContactPeopleInput,
  })
  @ValidateNested()
  @Type(() => AddressUpdateManyWithoutContactPeopleInput)
  @IsOptional()
  @Field(() => AddressUpdateManyWithoutContactPeopleInput, {
    nullable: true,
  })
  addresses?: AddressUpdateManyWithoutContactPeopleInput;

  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomerWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  department?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutContactPeopleInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutContactPeopleInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutContactPeopleInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutContactPeopleInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  phone?: number | null;
}

export { ContactPersonUpdateInput as ContactPersonUpdateInput };
