/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AddressCreateNestedManyWithoutContactPeopleInput } from "./AddressCreateNestedManyWithoutContactPeopleInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { OrderCreateNestedManyWithoutContactPeopleInput } from "./OrderCreateNestedManyWithoutContactPeopleInput";

@InputType()
class ContactPersonCreateInput {
  @ApiProperty({
    required: false,
    type: () => AddressCreateNestedManyWithoutContactPeopleInput,
  })
  @ValidateNested()
  @Type(() => AddressCreateNestedManyWithoutContactPeopleInput)
  @IsOptional()
  @Field(() => AddressCreateNestedManyWithoutContactPeopleInput, {
    nullable: true,
  })
  addresses?: AddressCreateNestedManyWithoutContactPeopleInput;

  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomerWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  department?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutContactPeopleInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutContactPeopleInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutContactPeopleInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutContactPeopleInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  phone?: number | null;
}

export { ContactPersonCreateInput as ContactPersonCreateInput };
